import Header from "@/components/header";
import "./globals.css";
import type { Metadata } from "next";
import Footer from "@/components/footer";

import { Inconsolata } from "next/font/google";

const inter = Inconsolata({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Project 1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body className={`flex min-h-screen flex-col items-center justify-between ${inter}`}> */}
      <body className={`flex min-h-screen flex-col items-center justify-between ${inter.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
