export const metadata = {
  title: "Project 1",
  description: "Generated by create next app",
};

export default async function Home() { 
  return (
    <main className="flex-1 mt-20 w-full">
      <section className="max-w-6xl mx-auto px-5 text-neutral-100">
        This is project 1
      </section>
    </main>
  );
}
