import { createServerSupabaseClient } from "@/clients/supabase-server-client";
import Image from "next/image";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Project 1",
  description: "Generated by create next app",
};

export default async function Profile() {
  const supabase = createServerSupabaseClient()
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    redirect("/sign-in");
  }

  return (
    <section className="flex-1 px-5 xl:px-0 mt-5">
      <div className="p-5 rounded-2xl border border-neutral-600 bg-neutral-800 shadow-md flex flex-col items-center sm:hidden">
        <div className="w-full border-b border-neutral-600 mb-5 pb-3 flex justify-center">
          <Image
            src="/default-profile-avatar.svg"
            width={75}
            height={75}
            className="rounded-full bg-white"
            alt="Profile Avatar"
          />
        </div>
        <div className="text-xl text-green-500 font-bold">
          {user.user_metadata.name}
        </div>
        <div className="text-lg text-green-500"> {user.email}</div>
      </div>
      <div className="p-5 rounded-2xl border border-neutral-600 bg-neutral-800 shadow-md hidden sm:flex items-center space-x-5 max-w-md">
        <div className="">
          <Image
            src="/default-profile-avatar.svg"
            width={75}
            height={75}
            className="rounded-full bg-white"
            alt="Profile Avatar"
          />
        </div>
        <div>
          <div className="text-xl text-green-500 font-bold">
            {user.user_metadata.name}
          </div>
          <div className="text-lg text-green-500"> {user.email}</div>
        </div>
      </div>
    </section>
  );
}
